### ISSUE TITLE
HITStatus() doesn't work properly

### ISSUE THREAD

**Issue by lilchow** [leeper/MTurkR#90] opened 2015-08-12 02:42 UTC
I have been encountering this issue the whole time. Whenever I use HITStatus to check the status of my newly launched HIT, it spills correct information for Assignment Pending and Assignment Available. However, Assignment Completed is always 0 regardless of whether a HIT is newly launched or newly completed. Any idea what is going on here? Thanks!

**Comment by leeper** [comment] 2015-08-12 07:15
I'm travelling at the moment, but give me a few days to investigate.

**Comment by leeper** [comment] 2015-10-28 10:16
As far as I can tell, there's nothing MTurkR-specific here because everything in the API responses is being parsed correctly. The issue is probably a lag in how AWS accumulates those results. So I'm closing this for now.

**Closed** 2016-02-11 11:21 UTC
Labels: bug
